version: '3.8'
services:
  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=mafiapp_db
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: