import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Link from "next/link";

export default function Home({ tasks }) {
  const [mobster, setMobster] = useState({});
  return (
    <div>
      <Head>
        <title>MafiaApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <h1>Hello, Mafia</h1>
        <ul>
          <li>
            <Link href="/tasks">Tasks</Link>
          </li>
          <li>
            <Link href="/missions">Missions</Link>
          </li>
        </ul>
        <p>
          Three reactionary security officials dedicated to “traditional values”
          and restoring Soviet glory will figure prominently in the decision
          whether to invade Ukraine. Flight data indicates that the launch on
          Sunday was the North’s most powerful since 2017. South Korean analysts
          expect further escalations from Kim Jong-un. A man with Covid revealed
          a parallel universe to well-off Chinese and became a symbol of
          inequality. The government found him inconvenient to its narrative.
          Because of a strong performance in the snap elections, the governing
          party will not have to form a coalition in the fractious Parliament.
          Plagued by plastic pollution, Senegal wants to replace pickers at the
          garbage dump with a formal recycling system that takes advantage of
          the new market for plastics. Brian Houston, who was the leader of
          Hillsong, is accused of concealing past abuse by his father, who later
          died and was never charged.
        </p>
        <button>Enter</button>
      </main>
    </div>
  );
}
